(()=>{"use strict";
const DB_NAME="k9-creative-studio-assets",DB_VERSION=1,STORE="assets",MAX_FILE=8*1024*1024;
const $=id=>document.getElementById(id);let dbPromise=null,objectUrls=new Map(),items=[];
function status(msg,error=false){const el=$("assetCenterStatus");if(el){el.textContent=msg;el.classList.toggle("error",error)}}
function openDb(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE)){const st=db.createObjectStore(STORE,{keyPath:"id"});st.createIndex("category","category");st.createIndex("updatedAt","updatedAt")}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return dbPromise}
async function tx(mode,fn){const db=await openDb();return new Promise((resolve,reject)=>{const t=db.transaction(STORE,mode),st=t.objectStore(STORE);let result;try{result=fn(st)}catch(e){reject(e);return}t.oncomplete=()=>resolve(result);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error)})}
async function all(){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function id(){return crypto.randomUUID?.()||`asset-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function guessCategory(file){const n=file.name.toLowerCase();if(/logo|marchio/.test(n))return"logo";if(/badge|stemma|timbro/.test(n))return"badge";if(/icon|icona/.test(n))return"icon";if(/texture|pattern/.test(n))return"texture";if(/frame|cornice/.test(n))return"frame";if(/background|sfondo/.test(n))return"background";return"photo"}
function safe(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function sizeLabel(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`}
function urlFor(a){if(objectUrls.has(a.id))return objectUrls.get(a.id);const u=URL.createObjectURL(a.blob);objectUrls.set(a.id,u);return u}
function cleanupUrls(){for(const u of objectUrls.values())URL.revokeObjectURL(u);objectUrls.clear()}
async function reload(){cleanupUrls();items=(await all()).sort((a,b)=>(b.favorite-a.favorite)||String(b.updatedAt).localeCompare(String(a.updatedAt)));render()}
function filtered(){const q=$("assetSearch")?.value.trim().toLowerCase()||"",cat=$("assetCategory")?.value||"all",fav=$("assetFavoritesOnly")?.checked;return items.filter(a=>(cat==="all"||a.category===cat)&&(!fav||a.favorite)&&(!q||[a.name,a.category,a.tags].join(" ").toLowerCase().includes(q)))}
function render(){const grid=$("assetGrid"),empty=$("assetEmpty"),list=filtered();if(!grid)return;grid.innerHTML=list.map(a=>`<article class="asset-card" data-id="${safe(a.id)}"><div class="asset-thumb"><img src="${urlFor(a)}" alt="${safe(a.name)}"><button class="asset-fav ${a.favorite?"active":""}" data-action="favorite" title="Preferito">★</button></div><div class="asset-body"><div class="asset-name" title="${safe(a.name)}">${safe(a.name)}</div><div class="asset-meta"><span>${safe(a.type||"immagine")}</span><span>${sizeLabel(a.size||0)}</span></div><select class="asset-category" aria-label="Categoria"><option value="logo" ${a.category==="logo"?"selected":""}>Logo</option><option value="photo" ${a.category==="photo"?"selected":""}>Fotografia</option><option value="background" ${a.category==="background"?"selected":""}>Sfondo</option><option value="badge" ${a.category==="badge"?"selected":""}>Badge</option><option value="icon" ${a.category==="icon"?"selected":""}>Icona</option><option value="texture" ${a.category==="texture"?"selected":""}>Texture</option><option value="frame" ${a.category==="frame"?"selected":""}>Cornice</option><option value="other" ${a.category==="other"?"selected":""}>Altro</option></select><input class="asset-tags" value="${safe(a.tags||"")}" placeholder="Tag separati da virgola"><div class="asset-actions"><button class="btn ok" data-action="apply">Usa</button><button class="btn" data-action="download">Scarica</button><button class="btn danger asset-delete" data-action="delete">Elimina</button></div></div></article>`).join("");empty.hidden=list.length!==0;$("assetStats").textContent=`${items.length} asset · ${sizeLabel(items.reduce((n,a)=>n+(a.size||0),0))}`}
async function addFiles(files){let added=0,skipped=0;for(const file of files){if(!file.type.startsWith("image/")||file.size>MAX_FILE){skipped++;continue}const now=new Date().toISOString();await tx("readwrite",st=>st.put({id:id(),name:file.name||"asset",type:file.type,size:file.size,category:guessCategory(file),tags:"",favorite:false,createdAt:now,updatedAt:now,blob:file}));added++}await reload();status(`${added} asset aggiunti${skipped?`; ${skipped} ignorati (formato o dimensione)`:""}.`)}
async function updateAsset(asset,changes){await tx("readwrite",st=>st.put({...asset,...changes,updatedAt:new Date().toISOString()}));await reload()}
function fileFrom(a){return new File([a.blob],a.name,{type:a.type||a.blob.type||"image/png"})}
function assignFile(input,file){try{const dt=new DataTransfer();dt.items.add(file);input.files=dt.files;input.dispatchEvent(new Event("change",{bubbles:true}));return true}catch(e){console.warn(e);return false}}
function apply(a){const target=a.category==="logo"?($("multiLogoUpload")||$("logoUpload")):$("imageUpload");if(!target)return status("Il progetto corrente non espone un campo compatibile.",true);if(assignFile(target,fileFrom(a))){document.querySelector('[data-tab="graphics"]')?.click();status(`Asset “${a.name}” applicato al progetto.`)}else status("Il browser non consente l'applicazione automatica. Usa Scarica e carica manualmente.",true)}
function download(a){const link=document.createElement("a");link.href=urlFor(a);link.download=a.name||"asset.png";link.click()}
async function remove(a){if(!confirm(`Eliminare “${a.name}” dalla libreria?`))return;await tx("readwrite",st=>st.delete(a.id));await reload();status("Asset eliminato.")}
async function cardAction(e){const card=e.target.closest(".asset-card");if(!card)return;const a=items.find(x=>x.id===card.dataset.id);if(!a)return;if(e.target.matches(".asset-category"))return updateAsset(a,{category:e.target.value});if(e.target.matches(".asset-tags"))return;const action=e.target.closest("[data-action]")?.dataset.action;if(action==="favorite")await updateAsset(a,{favorite:!a.favorite});if(action==="apply")apply(a);if(action==="download")download(a);if(action==="delete")await remove(a)}
async function cardChange(e){const card=e.target.closest(".asset-card"),a=items.find(x=>x.id===card?.dataset.id);if(a&&e.target.matches(".asset-tags"))await updateAsset(a,{tags:e.target.value.trim()})}
function blobToData(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
async function exportLibrary(){status("Preparazione backup…");const payload=[];for(const a of items)payload.push({...a,blob:undefined,data:await blobToData(a.blob)});const out={schema:"k9-asset-center",version:1,exportedAt:new Date().toISOString(),assets:payload},blob=new Blob([JSON.stringify(out)],{type:"application/json"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`k9-asset-library-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);status("Backup della libreria esportato.")}
function dataToBlob(data){const [meta,b64]=data.split(","),type=(meta.match(/data:(.*?);/)||[])[1]||"image/png",bin=atob(b64),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new Blob([arr],{type})}
async function importLibrary(file){try{const data=JSON.parse(await file.text());if(data.schema!=="k9-asset-center"||!Array.isArray(data.assets))throw new Error("Backup non valido");let count=0;for(const raw of data.assets){if(!raw.data)continue;const blob=dataToBlob(raw.data),now=new Date().toISOString();await tx("readwrite",st=>st.put({...raw,id:id(),blob,data:undefined,size:blob.size,createdAt:raw.createdAt||now,updatedAt:now}));count++}await reload();status(`${count} asset importati.`)}catch(e){status(e.message||"Importazione non riuscita.",true)}}
async function clearAll(){if(!items.length)return;if(!confirm("Eliminare definitivamente tutti gli asset locali?"))return;await tx("readwrite",st=>st.clear());await reload();status("Libreria svuotata.")}
function bind(){$("assetUpload")?.addEventListener("change",e=>{addFiles([...e.target.files]);e.target.value=""});["assetSearch","assetCategory","assetFavoritesOnly"].forEach(id=>$(id)?.addEventListener("input",render));$("assetGrid")?.addEventListener("click",cardAction);$("assetGrid")?.addEventListener("change",cardChange);$("assetExport")?.addEventListener("click",exportLibrary);$("assetImportBtn")?.addEventListener("click",()=>$("assetImport")?.click());$("assetImport")?.addEventListener("change",e=>{if(e.target.files[0])importLibrary(e.target.files[0]);e.target.value=""});$("assetClear")?.addEventListener("click",clearAll);window.addEventListener("beforeunload",cleanupUrls)}
async function init(){if(!("indexedDB" in window)){status("IndexedDB non è disponibile in questo browser.",true);return}bind();try{await reload();status("Asset Center pronto. I file restano nel dispositivo e funzionano offline.")}catch(e){console.error(e);status("Impossibile aprire la libreria locale.",true)}}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init();
})();
